distiller_config: "/exports/igmm/eddie/wendy-lab/ilia/remainers/distiller_project.yml"
path_genomes: "/exports/igmm/eddie/wendy-lab/ilia/genomes"
path_coolers: "/exports/igmm/eddie/wendy-lab/ilia/remainers/coolers"
path_expected: "/exports/igmm/eddie/wendy-lab/ilia/remainers/coolers/expected"
path_eigenvectors: "/exports/igmm/eddie/wendy-lab/ilia/remainers/coolers/eigenvectors"
eigenvector_resolutions_min: 50000
