genome: hg38
path_genome_folder: resources/genome/
path_genome_fasta: resources/genome/hg38.fa
chromsizes: resources/genome/hg38_chromsizes.txt
view: resources/view1.txt

# Samples file with two columns: sample name ("sample") and path/url with cool file ("file").
# If it's URL, it will be downloaded. If the file is already downloaded it will not be overwritten.
# The downloaded file will be stored as {coolers_folder}/{sample}.mcool
samples: config/samples.tsv
# Annotations file with two columns: annotation name ("bedname") and "file" (URLs or local file)
# Downloaded bed files will be stored in beds_folder
annotations: config/annotations.tsv
# Rules about correpondence between samples and annotations can be specified here
samples_annotations_combinations: config/samples_annotations.tsv

# folder definition is optional
# by default everything is done using inputs in inputs/
# and results saved in results/
inputs_folder: inputs
beds_folder: inputs/beds
bedpes_folder: inputs/bedpes
coolers_folder: inputs/coolers

project_folder: results
expected_folder: results/expected
pileups_folder: results/pileups
eigenvectors_folder: results/eigenvectors
saddles_folder: results/saddles
insulation_folder: results/insulation
tad_folder: results/tads
loop_folder: results/loops
boundary_folder: results/boundaries
interchrom_folder: results/interchrom
plot_folder: results/plots

resolutions:
    - 1000000
    - 100000
    - 10000
    - 1000
ignore_resolutions_more_than: 1000000

eigenvector:
    do: True
    resolution_limits:
        - 10000
        - 100000
saddle:
    do: True
    bins:
        - 100
    distance_limits:
        - 1600000
        - 102400000
    range: "--qrange 0.01 0.99 "
    extra: "--strength"

pileups:
    do: True
    resolution_limits:
        - 5000
        - 10000
    distance_limits:
        - 500000
        - 12000000
        # - 12500
        # - 102400000
    shifts: 0
    expected: True
    ooe: True #Only applies when expected is True
    arguments:
        distal: "--maxdist 2000000"
        by_distance: "--by_distance"
        local: "--local"
        local_rescaled: '--local --rescale --rescale_pad 1'
        by_strand_by_distance: "--by_strand --by_distance"
        by_strand_local: "--by_strand --local"
        by_strand_distal: "--by_strand --maxdist 1000000"
        by_window_short_range: "--by_window --subset 1000 --maxdist 2000000"
        by_window_long_range:  "--by_window --subset 1000 --mindist 2000000"

insulation:
    do: True
    resolutions:
        1000:
            - 3000 # What window sizes to do for what resolution
            - 5000
            - 10000
            - 25000
        10000:
            - 50000
            - 100000
    extra: '--chunksize 1000000000 --threshold Li' # Choose between a specific float, Li or Otsu, see https://github.com/open2c/open2c_examples/blob/master/Insulation_and_boundaries.ipynb

call_dots:
    methods:
        cooltools:
            do: True
            extra: "--max-loci-separation 10000000 --fdr 0.02"
        chromosight:
            do: False
            extra: ""
        mustache:
            do: False
            max_dist: 10000000
            extra: "-pt 0.05 -st 0.8"
    resolutions:
        - 10000
    samples:
        - Y1

compare_boundaries:
    do: True
    samples:
        - Y1
        - O1
    fold_change_threshold: 5

call_TADs: # By just combining strong boundaries
    do: True
    resolutions:
        10000: # Which window sizes to use for which resolution
            - 50000
            - 100000
            - 200000
    max_tad_length: 1500000
    samples:
        - Y1
        - O1

interchroms:
    do: True
    resolution: 100000

compare_interchroms:
    pairs: # - nominator / denominator 
        - O1 Y1
        - O1 Y2
        - O2 Y1
        - O2 Y2

scaling_ratio:
    do: True
    windows:
        - 10
        - 50
        - 100
    max_dists:
        - 2_000_000
        - 30_000_000
    pairs: # - nominator / denominator 
        - O1 Y1
        - O1 Y2
        - O2 Y1
        - O2 Y2

eigenvectors_correlation:
    do: True
    eig:
        - E1
        - E2
        - best #best means that the eigenvector with largest corresponding value of lambda

tad_ratio:
    do: True
    pairs: # - nominator / denominator; note that paired samples should be present in call_tad config
        - O1 Y1

loop_ratio: #currently only for cooltools loops
    do: True
    pairs: # - nominator / denominator; note that paired samples should be present in call_dots config
        - O1 Y1