name: quaich
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.7
  - pip
  - cython
  - snakemake
  - cooler
  - chromosight
  - ucsc-bedgraphtobigwig
  - scikit-image
  - tqdm
  - pip:
    - cooltools
    - https://github.com/open2c/coolpuppy/archive/master.zip