name: quaich
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - mamba
  - pip
  - cython
  - snakemake
  - cooler
  - ucsc-bedgraphtobigwig
  - bioframe>=0.3.3
  - tqdm
  - toolz
  - cooltools
  - seaborn=0.12.2
  - coolpuppy=1.0.0
  - tables=3.8.0
